services:
  app-service:
    build: .
    container_name: sample-app
    restart: always
    env_file: .env.example
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    external: true
